import assert from 'node:assert/strict';
import { emptyAction } from '../src/brain/action.ts';
import { actionToItem } from '../src/brain/toItem.ts';
import { overdueItems, shoppingDuplicate } from '../src/store/planning.ts';
import { answerQuery, queryItems } from '../src/store/query.ts';
import { validatePlanLinks } from '../src/store/linkedItems.ts';
const past = { ...actionToItem(emptyAction('create_todo', 'จ่ายค่าเน็ต'))!, start_at: '2026-09-06T09:00:00+07:00' };
const now = new Date('2026-09-07T12:00:00+07:00');
const done = { ...past, id: 'done', done: true };
const recurring = { ...past, id: 'recurring', recurrence: { freq: 'daily' as const, interval: 1, byday: null } };
assert.deepEqual(overdueItems([past, done, recurring], now).map((i) => i.id), [past.id]);
const query = { ...emptyAction('query'), query_kind: 'briefing' as const };
assert.ok(answerQuery([past], query, now).includes('จ่ายค่าเน็ต'));
assert.deepEqual(queryItems([past], query, now).map((i) => i.id), [past.id]);
const product = actionToItem({ ...emptyAction('add_shopping', 'ไข่'), quantity: 2, unit: 'แผง', list_name: 'ตลาดวันเสาร์' })!;
assert.equal(product.details?.shopping?.quantity, 2);
assert.equal(shoppingDuplicate([product], product)?.id, product.id);
assert.equal(shoppingDuplicate([{ ...product, household_id: 'other-space' }], product), undefined);
assert.equal(shoppingDuplicate([{ ...product, done: true }], product), undefined);
assert.equal(shoppingDuplicate([product], { ...product, details: { shopping: { ...product.details!.shopping!, unit: 'ฟอง' } } }), undefined);
const event = { ...emptyAction('create_event'), datetime: '2026-09-08T10:00:00+07:00' };
const reminder = { ...emptyAction('create_reminder'), datetime: '2026-09-08T09:00:00+07:00', parent_ref: 'action:1' };
assert.doesNotThrow(() => validatePlanLinks([event, reminder], [], () => null));
assert.throws(() => validatePlanLinks([reminder, event], [], () => null));
assert.throws(() => validatePlanLinks([event, reminder], [], (a) => a.tool === 'create_event' ? 'one' : 'two'));
console.log('✓ overdue tasks, briefing referents, shopping units/duplicates and whole-plan link validation');
