import assert from 'node:assert/strict';
import { emptyAction } from '../src/brain/action.ts';
import { actionToItem } from '../src/brain/toItem.ts';
import { occurrenceDates, occurrencePatch, occursOn } from '../src/domain/recurrence.ts';
import { assignmentPatch, receivesAlert } from '../src/domain/assignment.ts';
import { busySlots, freeSlots } from '../src/domain/availability.ts';
import { changeDefaults, initialDefaults, replyLanguage } from '../src/domain/defaults.ts';
import { memoryBatches } from '../src/brain/searchMemory.ts';
import { capabilityAnswer } from '../src/help/capabilities.ts';
import { answerQuery } from '../src/store/query.ts';
const item = { ...actionToItem(emptyAction('create_event', 'Meeting'))!, start_at:'2026-09-07T09:00:00+07:00', end_at:'2026-09-07T10:00:00+07:00', recurrence:{freq:'daily' as const,interval:1,byday:null} };
const from = new Date('2026-09-07T00:00:00+07:00'), to = new Date('2026-09-10T00:00:00+07:00');
assert.equal(occurrenceDates(item,from,to).length,3);
const skipped = {...item,...occurrencePatch(item,'2026-09-08','skipped')};
assert.equal(skipped.done,false); assert.equal(occurrenceDates(skipped,from,to).length,2);
assert.equal(occurrenceDates({...skipped,...occurrencePatch(skipped,'2026-09-08','pending')},from,to).length,3);
assert.throws(()=>occurrencePatch(item,'2026-02-30','done'));
const biweekly={...item,recurrence:{freq:'weekly' as const, interval:2,byday:['MO' as const]}};
assert.equal(occursOn(biweekly,new Date('2026-09-14T12:00:00+07:00')),false);
assert.equal(occursOn(biweekly,new Date('2026-09-21T12:00:00+07:00')),true);
const monthly={...item,start_at:'2026-01-31T09:00:00+07:00',recurrence:{freq:'monthly' as const,interval:1,byday:null}};
assert.equal(occursOn(monthly,new Date('2026-02-28T12:00:00+07:00')),false);
assert.equal(occursOn(monthly,new Date('2026-03-31T12:00:00+07:00')),true);
const shared={...item,household_id:'space'};
const members=[{user_id:'one',name:'A'},{user_id:'two',name:'B'}];
const assigned={...shared,...assignmentPatch(shared,'one',['two'],members)};
assert.equal(receivesAlert(assigned,'one'),false); assert.equal(receivesAlert(assigned,'two'),true);
assert.equal(receivesAlert(shared,null),false); assert.equal(receivesAlert(shared,'one'),true);
assert.throws(()=>assignmentPatch(shared,'outsider',null,members));
assert.equal(receivesAlert({...shared,...assignmentPatch(shared,null,[],members)},'one'),false);
const start=new Date('2026-09-08T08:00:00+07:00'),end=new Date('2026-09-08T12:00:00+07:00');
assert.equal(freeSlots([item],start,end,60).length,2);
assert.equal(freeSlots([skipped],start,end,60).length,1);
assert.equal(busySlots([item],new Date('2026-09-08T10:00:00+07:00'),end).length,0);
assert.throws(()=>freeSlots([],new Date('invalid'),end,60));
assert.throws(()=>freeSlots([],start,end,-1));
assert.equal(changeDefaults(initialDefaults,'หลังเลิกงาน','18:30').timePhrases['หลังเลิกงาน'],'18:30');
assert.throws(()=>changeDefaults(initialDefaults,'ตอนเช้า','25:00'));
assert.equal(changeDefaults(initialDefaults,'reminder_lead_minutes','15').leadMinutes,15);
assert.equal(replyLanguage('auto','hello'),'en'); assert.equal(replyLanguage('auto','สวัสดี'),'th'); assert.equal(replyLanguage('en','สวัสดี'),'en');
const records=Array.from({length:350},(_,n)=>({...item,id:String(n),body:'x'.repeat(n===349?40000:500)}));
const batches=memoryBatches(records); const ids=new Set(batches.flat().map((r)=>r.id));
assert.equal(ids.size,350); assert.ok(batches.flat().filter((r)=>r.id==='349').map((r)=>r.text).join('').includes('x'.repeat(40000)));
assert.match(answerQuery([item],emptyAction('query'),from,'th'),/เวลา 9:00/);
assert.match(capabilityAnswer({web:true,budget:false,shared:true},'en'),/Web Push/);
console.log('✓ assignment/audience, recurring skip/reopen/intervals, availability boundaries, defaults/languages, full-history batching');
