import assert from 'node:assert/strict';
import { entityContext, validateEntityLinks } from '../src/knowledge/entities.ts';
import { linkedChildren, linkedPatches } from '../src/store/linkedItems.ts';
import { actionToItem } from '../src/brain/toItem.ts';
import { emptyAction } from '../src/brain/action.ts';
import type { Item } from '../src/store/types.ts';
const parent = { ...actionToItem(emptyAction('create_event', 'นัดหมอ'))!, id: 'parent', start_at: '2026-09-07T10:00:00+07:00', household_id: 'space-a' };
const child: Item = { ...actionToItem(emptyAction('create_reminder', 'เตือนนัดหมอ'))!, id: 'child', start_at: '2026-09-07T09:00:00+07:00', household_id: 'space-a', details: { parent_id: 'parent', reminder_offset_minutes: -60 } };
const other: Item = { ...child, id: 'other', household_id: 'space-b' };
assert.deepEqual(linkedChildren([parent, child, other], parent).map((i) => i.id), ['child']);
const shifted = linkedPatches([parent, child, other], parent, { start_at: '2026-09-09T11:00:00+07:00' });
assert.equal(shifted[0].patch.start_at, '2026-09-09T03:00:00.000Z');
assert.equal(linkedPatches([child], parent, { done: true })[0].patch.done, true);
assert.equal(linkedPatches([child], parent, { title: 'new title' }).length, 0);
const entity = { ...actionToItem({ ...emptyAction('remember_entity', 'โมจิ'), entity_kind: 'pet' })!, id: 'pet' };
assert.equal(entity.details?.profile?.kind, 'pet');
assert.equal(entity.start_at, null);
assert.deepEqual(validateEntityLinks(['pet', 'pet'], null, [entity]), ['pet']);
assert.throws(() => validateEntityLinks(['pet'], 'space-a', [entity]));
assert.throws(() => validateEntityLinks(['missing'], null, [entity]));
assert.deepEqual(entityContext([entity], { pet: ['แมวเรา'] })[0].aliases, ['แมวเรา']);
assert.deepEqual(entityContext([entity], {})[0].aliases, []);
console.log('✓ scoped entities, private aliases, linked reminder shifts, completion and isolation');
